export default [
  "Wages",
  "Sales",
  "Passive Income",
  "Gambling",
  "Dividends",
  "Misc. Income",
  "Housing",
  "Restaurants",
  "Groceries",
  "Shopping",
  "Insurance",
  "Transportation",
  "Education",
  "Leisure",
  "Telecommunications",
  "Tax",
  "Health & Beauty",
  "Misc. Expense",
  "Init. Account",
];
